drone-runner-kube:
  extraSecretNamesForEnvFrom:
    - droneci-secrets
  env:
    DRONE_NAMESPACE_DEFAULT: drone-runner
    DRONE_RPC_HOST: drone.zanelab.com
    DRONE_RPC_PROTO: https
    DRONE_RUNNER_PRIVILEGED_IMAGES: docker/dind

  rbac:
    buildNamespaces:
      - drone-runner