seafile:
  image:
    repository: seafileltd/seafile-mc
    tag: 11.0.0
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/proxy-body-size: 0m
        external-dns.alpha.kubernetes.io/target: "homelab-prod-tunnel.zanelab.com"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hosts:
        - host: &host seafile.zanelab.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: seafile-tls-certificate
          hosts:
            - *host
  persistence:
    data:
      enabled: true
      mountPath: /shared
      type: pvc
      readOnly: false
      storageClass: freenas-nfs-csi
      accessMode: ReadWriteOnce
      size: 100Gi

  mariadb:
    enabled: true
    primary:
      persistence:
        enabled: true
        readOnly: false
        storageClass: freenas-nfs-csi
        size: 10Gi

